### ISSUE TITLE
AxiosError

### ISSUE THREAD

**Issue by somfist** [Broccoli-Velog/Broccoli-Frontend#12]
AxiosError {message: 'Unsupported protocol localhost:', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}}
code: "ERR_BAD_REQUEST"
config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
message: "Unsupported protocol localhost:"
name: "AxiosError"
[[Prototype]]: Error
![image](https://user-images.githubusercontent.com/89966037/181917003-9eb77f38-09aa-407a-86f0-3a5fb83df469.png)

**Comment by somfist** [comment]
![image](https://user-images.githubusercontent.com/89966037/181917478-aee421f6-09b7-403b-89fb-43dc7b3db5d9.png)

Access to XMLHttpRequest at 'localhost:4000/' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

Error: Network Error
    at createError (createError.js:16:1)
    at XMLHttpRequest.handleError (xhr.js:117:1)

xhr.js:210          POST localhost:4000/ net::ERR_FAILED
